/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Anitabonita
 */
public class GestionSpa extends javax.swing.JFrame {

    /**
     * Creates new form GestionSpa
     */
    public GestionSpa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMCliente = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnVerTratamientos = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        btnGestionConsultorios = new javax.swing.JMenuItem();
        menuTurno = new javax.swing.JMenu();
        btnConsultarTurnos = new javax.swing.JCheckBoxMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        itemConsultas = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText(" Clientes");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMCliente.setText("Gestionar Clientes");
        jMCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMCliente);

        jMenuBar1.add(jMenu1);

        jMenu7.setText("Especialistas");

        jMenuItem2.setText("Gestion especialistas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem2);

        jMenuBar1.add(jMenu7);

        jMenu3.setText("Instalaciones");

        jMenuItem1.setText("Gestion Instalación");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Tratamientos");

        btnVerTratamientos.setText("Ver Tratamientos");
        btnVerTratamientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTratamientosActionPerformed(evt);
            }
        });
        jMenu2.add(btnVerTratamientos);

        jMenuBar1.add(jMenu2);

        jMenu8.setText("Consultorio");

        btnGestionConsultorios.setText("Gestionar Consultorios");
        btnGestionConsultorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionConsultoriosActionPerformed(evt);
            }
        });
        jMenu8.add(btnGestionConsultorios);

        jMenuBar1.add(jMenu8);

        menuTurno.setText("Turnos");

        btnConsultarTurnos.setSelected(true);
        btnConsultarTurnos.setText("Consultar Turnos");
        btnConsultarTurnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarTurnosActionPerformed(evt);
            }
        });
        menuTurno.add(btnConsultarTurnos);

        jMenuBar1.add(menuTurno);

        jMenu10.setText("Spa");
        jMenu10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu10ActionPerformed(evt);
            }
        });

        jMenuItem4.setText("Gestionar spa");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem4);

        jMenuBar1.add(jMenu10);

        jMenu9.setText("Consultas");
        jMenu9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu9ActionPerformed(evt);
            }
        });

        itemConsultas.setText("Consultas");
        itemConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultasActionPerformed(evt);
            }
        });
        jMenu9.add(itemConsultas);

        jMenuItem3.setText("jMenuItem3");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem3);

        jMenuItem5.setText("Informe Dias de Spa");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem5);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1184, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your h here:

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMClienteActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaCliente vc = new VistaCliente();
        vc.setLocation(
                (escritorio.getWidth() - vc.getWidth()) / 2,
                (escritorio.getHeight() - vc.getHeight()) / 2
        );
        vc.setVisible(true);
        escritorio.add(vc);
        escritorio.moveToFront(vc);
    }//GEN-LAST:event_jMClienteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaInstalacion vi = new VistaInstalacion();
        vi.setLocation(
                (escritorio.getWidth() - vi.getWidth()) / 2,
                (escritorio.getHeight() - vi.getHeight()) / 2
        );
        vi.setVisible(true);
        escritorio.add(vi);
        escritorio.moveToFront(vi);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaEspecialista ve = new VistaEspecialista();
        ve.setLocation(
                (escritorio.getWidth() - ve.getWidth()) / 2,
                (escritorio.getHeight() - ve.getHeight()) / 2
        );
        escritorio.add(ve);
        ve.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnVerTratamientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTratamientosActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaTratamiento ve = new VistaTratamiento();
        ve.setLocation(
                (escritorio.getWidth() - ve.getWidth()) / 2,
                (escritorio.getHeight() - ve.getHeight()) / 2
        );
        escritorio.add(ve);
        ve.setVisible(true);
    }//GEN-LAST:event_btnVerTratamientosActionPerformed

    private void btnGestionConsultoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionConsultoriosActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaConsultorio ve = new VistaConsultorio();
        ve.setLocation(
                (escritorio.getWidth() - ve.getWidth()) / 2,
                (escritorio.getHeight() - ve.getHeight()) / 2
        );
        escritorio.add(ve);
        ve.setVisible(true);
    }//GEN-LAST:event_btnGestionConsultoriosActionPerformed

    private void btnConsultarTurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarTurnosActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaTurno ve = new VistaTurno();
        ve.setLocation(
                (escritorio.getWidth() - ve.getWidth()) / 2,
                (escritorio.getHeight() - ve.getHeight()) / 2
        );
        escritorio.add(ve);
        ve.setVisible(true);
    }//GEN-LAST:event_btnConsultarTurnosActionPerformed

    private void jMenu10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu10ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jMenu10ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaDiaDeSpa vc = new VistaDiaDeSpa();
        vc.setLocation(
                (escritorio.getWidth() - vc.getWidth()) / 2,
                (escritorio.getHeight() - vc.getHeight()) / 2
        );
        escritorio.add(vc);

        vc.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void itemConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultasActionPerformed
         escritorio.removeAll();
        escritorio.repaint();
        SistemaConsultas vc = new SistemaConsultas();
        vc.setLocation(
                (escritorio.getWidth() - vc.getWidth()) / 2,
                (escritorio.getHeight() - vc.getHeight()) / 2
        );
        escritorio.add(vc);

        vc.setVisible(true);
    }//GEN-LAST:event_itemConsultasActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaDiaDeSpaCompleto vc = new VistaDiaDeSpaCompleto();
        vc.setLocation(
                (escritorio.getWidth() - vc.getWidth()) / 2,
                (escritorio.getHeight() - vc.getHeight()) / 2
        );
        escritorio.add(vc);

        vc.setVisible(true);
          
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu9ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaDiaDeSpaCompleto vc = new VistaDiaDeSpaCompleto();
        vc.setLocation(
                (escritorio.getWidth() - vc.getWidth()) / 2,
                (escritorio.getHeight() - vc.getHeight()) / 2
        );
        escritorio.add(vc);

        vc.setVisible(true);
    }//GEN-LAST:event_jMenu9ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        InformeDiaDeSpa vc = new InformeDiaDeSpa();
        vc.setLocation(
                (escritorio.getWidth() - vc.getWidth()) / 2,
                (escritorio.getHeight() - vc.getHeight()) / 2
        );
        escritorio.add(vc);

        vc.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionSpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionSpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionSpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionSpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionSpa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem btnConsultarTurnos;
    private javax.swing.JMenuItem btnGestionConsultorios;
    private javax.swing.JMenuItem btnVerTratamientos;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem itemConsultas;
    private javax.swing.JMenuItem jMCliente;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenu menuTurno;
    // End of variables declaration//GEN-END:variables
}
