/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.DiaDeSpa;
import Persistencia.DiaDeSpaData;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anitabonita
 */
public class InformeDiaDeSpa extends javax.swing.JInternalFrame {

    private DiaDeSpaData diaSpaData = new DiaDeSpaData();
    private DefaultTableModel modeloTabla = new DefaultTableModel();

    /**
     * Creates new form InformeDiaDeSpa
     */
    public InformeDiaDeSpa() {
        initComponents();
        armarCabeceraTabla();
        cargarFechaActual();
    }
    
    private void armarCabeceraTabla() {
        modeloTabla.addColumn("Código");
        modeloTabla.addColumn("Cliente");
        modeloTabla.addColumn("DNI");
        modeloTabla.addColumn("Hora");
        modeloTabla.addColumn("Servicios");
        modeloTabla.addColumn("Total");
        modeloTabla.addColumn("Estado");
        jTable1.setModel(modeloTabla);
    }
     private void cargarFechaActual() {
        jDateChooser1.setDate(new java.util.Date());
    }

    private void generarInforme() {
    if (jDateChooser1.getDate() == null) {
        JOptionPane.showMessageDialog(this, "Seleccione una fecha");
        return;
    }

    // Convertir java.util.Date a java.sql.Date
    java.util.Date fechaUtil = jDateChooser1.getDate();
    java.sql.Date fechaSQL = new java.sql.Date(fechaUtil.getTime());

    // Limpiar tabla
    modeloTabla.setRowCount(0);

    // Buscar días de spa para la fecha seleccionada
    List<DiaDeSpa> diasSpa = diaSpaData.buscarDiasDeSpaPorFecha(fechaSQL);

    if (diasSpa.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "No hay días de spa registrados para la fecha seleccionada");
        limpiarResumen();
        return;
    }

    double ingresosTotales = 0;
    int clientesAtendidos = 0;

    // Llenar tabla con los datos
    for (DiaDeSpa dia : diasSpa) {
        if (dia.getCliente() != null) {
            double totalDia = calcularTotalDia(dia);
            ingresosTotales += totalDia;
            clientesAtendidos++;

            Object[] fila = {
                dia.getCodPack(),
                dia.getCliente().getNombreCompleto(),
                dia.getCliente().getDni(),
                dia.getFechaYHora().getHour() + ":" + 
                String.format("%02d", dia.getFechaYHora().getMinute()),
                dia.getSesiones() != null ? dia.getSesiones().size() + " servicios" : "0 servicios",
                "$" + String.format("%.2f", totalDia),
                obtenerEstado(dia)
            };
            modeloTabla.addRow(fila);
        }
    }

    // Actualizar resumen
    actualizarResumen(diasSpa.size(), ingresosTotales, clientesAtendidos);
}
     private double calcularTotalDia(DiaDeSpa dia) {
        try {
            return dia.getSesiones().stream()
                    .mapToDouble(sesion -> sesion.getTratamiento() != null ? 
                        sesion.getTratamiento().getCosto() : 0)
                    .sum();
        } catch (Exception e) {
            return 0.0;
        }
    }

    private String obtenerEstado(DiaDeSpa dia) {
        if (dia.getFechaYHora().isBefore(java.time.LocalDateTime.now())) {
            return "Completado";
        } else {
            return "Pendiente";
        }
    }

    private void actualizarResumen(int totalDias, double ingresos, int clientes) {
        lblTotalDiasLabel.setText(String.valueOf(totalDias));
        lblIngresos.setText("$" + String.format("%.2f", ingresos));
        lblClientes.setText(String.valueOf(clientes));
    }

    private void limpiarResumen() {
        lblTotalDiasLabel.setText("0");
        lblIngresos.setText("$0.00");
        lblClientes.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        btnGenerar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelResumen = new javax.swing.JPanel();
        lblTituloResumen = new javax.swing.JLabel();
        lblIngresosLabel = new javax.swing.JLabel();
        lblClientesLabel = new javax.swing.JLabel();
        lblTotalDiasLabel = new javax.swing.JLabel();
        lblIngresos = new javax.swing.JLabel();
        lblClientes = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setTitle("Informe Dias de Spa");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Seleccione la fecha: ");

        btnGenerar.setBackground(new java.awt.Color(0, 153, 255));
        btnGenerar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGenerar.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerar.setText("Generar Informe");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        panelResumen.setBackground(new java.awt.Color(0, 153, 255));
        panelResumen.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESUMEN DEL DIA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        panelResumen.setForeground(new java.awt.Color(255, 255, 255));

        lblTituloResumen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTituloResumen.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloResumen.setText("Total Dias de Spa:");

        lblIngresosLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIngresosLabel.setForeground(new java.awt.Color(255, 255, 255));
        lblIngresosLabel.setText("Ingresos totales:");

        lblClientesLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblClientesLabel.setForeground(new java.awt.Color(255, 255, 255));
        lblClientesLabel.setText("Cantidad de Clientes:");

        lblTotalDiasLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalDiasLabel.setForeground(new java.awt.Color(255, 255, 255));

        lblIngresos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIngresos.setForeground(new java.awt.Color(255, 255, 255));

        lblClientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblClientes.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelResumenLayout = new javax.swing.GroupLayout(panelResumen);
        panelResumen.setLayout(panelResumenLayout);
        panelResumenLayout.setHorizontalGroup(
            panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResumenLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblClientesLabel)
                    .addComponent(lblIngresosLabel)
                    .addComponent(lblTituloResumen))
                .addGap(47, 47, 47)
                .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIngresos)
                    .addComponent(lblTotalDiasLabel)
                    .addComponent(lblClientes))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        panelResumenLayout.setVerticalGroup(
            panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResumenLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloResumen)
                    .addComponent(lblTotalDiasLabel))
                .addGap(18, 18, 18)
                .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIngresosLabel)
                    .addComponent(lblIngresos))
                .addGap(18, 18, 18)
                .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClientesLabel)
                    .addComponent(lblClientes))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("INFORME DIARIO DE DIAS DE SPA");

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(panelResumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(167, 167, 167)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnGenerar)))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(28, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelResumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        generarInforme();
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblClientesLabel;
    private javax.swing.JLabel lblIngresos;
    private javax.swing.JLabel lblIngresosLabel;
    private javax.swing.JLabel lblTituloResumen;
    private javax.swing.JLabel lblTotalDiasLabel;
    private javax.swing.JPanel panelResumen;
    // End of variables declaration//GEN-END:variables
}
