/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import com.toedter.calendar.JDateChooser;
import java.awt.event.ActionEvent;
import java.sql.Date;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author maria
 */
public class PagoTarjeta extends javax.swing.JDialog {

    private boolean pago = false;
    private JDateChooser dateVencimiento;

    /**
     * Creates new form PagoTarjeta
     */
    public PagoTarjeta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        configurarRadioButtons();
        campos();
        setLocationRelativeTo(parent);
        ButtonGroup grupoTipos = new ButtonGroup();
        grupoTipos.add(radioTrajeta);
        grupoTipos.add(radioTrasferencia);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void configurarRadioButtons() {
        radioTrajeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campos();
            }
        });

        radioTrasferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campos();
            }
        });
    }

    

    private void campos() {
   
        textNombre.setEnabled(false);
        textCodigo.setEnabled(false);
        textTarjeta.setEnabled(false);
        textNombreApellido.setEnabled(false);
        labelcvu.setEnabled(false);
        fechaVencimiento.setEnabled(false);

        if (radioTrajeta.isSelected()) {
            textNombre.setEnabled(true);
            textCodigo.setEnabled(true);
            textTarjeta.setEnabled(true);
            fechaVencimiento.setEnabled(true);
        } else if (radioTrasferencia.isSelected()) {
            textNombreApellido.setEnabled(true);
            labelcvu.setEnabled(true);
        }

        if (!radioTrajeta.isSelected()) {
            textTarjeta.setText("");
            textNombre.setText("");
            textCodigo.setText("");
            fechaVencimiento.setDate(null);
        }

        if (!radioTrasferencia.isSelected()) {
            textNombreApellido.setText("");
        }
    }

   private boolean validaciones() {
        if (!radioTrajeta.isSelected() && !radioTrasferencia.isSelected()) {
            JOptionPane.showMessageDialog(this, "Seleccione un método de pago", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (radioTrajeta.isSelected()) {
            if (textTarjeta.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese el número de tarjeta", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            if (textNombre.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese el nombre del titular", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            if (textCodigo.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese el código de seguridad", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            if (fechaVencimiento.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Seleccione la fecha de vencimiento", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            java.util.Date hoy = new java.util.Date();
            if (fechaVencimiento.getDate().before(hoy)) {
                JOptionPane.showMessageDialog(this, "La tarjeta está vencida", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            String tarjeta = textTarjeta.getText().replaceAll("\\s+", "");
            if (!tarjeta.matches("\\d{16}")) {
                JOptionPane.showMessageDialog(this, "El número de tarjeta debe tener 16 dígitos", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            if (!textCodigo.getText().matches("\\d{3,4}")) {
                JOptionPane.showMessageDialog(this, "El código de seguridad debe tener 3 o 4 dígitos", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }

        } else if (radioTrasferencia.isSelected()) {
            if (textNombreApellido.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese su nombre y apellido", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
        
        return true;
    }



    public boolean pagoEfectuado() {
        return pago;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoPago = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        radioTrajeta = new javax.swing.JRadioButton();
        radioTrasferencia = new javax.swing.JRadioButton();
        textTarjeta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        textCodigo = new javax.swing.JTextField();
        btnPagar = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        textNombreApellido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        labelcvu = new javax.swing.JLabel();
        fechaVencimiento = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pago Tratamiento");

        dialogoPago.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 102, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setText("<html><u>Seleccione el medio de pago</u></html>");

        radioTrajeta.setForeground(new java.awt.Color(255, 102, 51));
        radioTrajeta.setText("Tarjeta Credito/Debito");

        radioTrasferencia.setForeground(new java.awt.Color(255, 102, 51));
        radioTrasferencia.setText("Transferencia");

        jLabel2.setForeground(new java.awt.Color(255, 102, 51));
        jLabel2.setText("Nº de la tarjeta:");

        jLabel3.setForeground(new java.awt.Color(255, 102, 51));
        jLabel3.setText("Nombre Titular:");

        jLabel4.setForeground(new java.awt.Color(255, 102, 51));
        jLabel4.setText("Fecha de Vencimiento:");

        jLabel5.setForeground(new java.awt.Color(255, 102, 51));
        jLabel5.setText("Cod. de Seg:");

        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 102, 51));
        jLabel6.setText("Nombre y Apellido:");

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Enviar comprobante de pago al 2664863827");

        labelcvu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelcvu.setForeground(new java.awt.Color(255, 102, 51));
        labelcvu.setText("CBU: 0000044550357739302920");

        javax.swing.GroupLayout dialogoPagoLayout = new javax.swing.GroupLayout(dialogoPago);
        dialogoPago.setLayout(dialogoPagoLayout);
        dialogoPagoLayout.setHorizontalGroup(
            dialogoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoPagoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(dialogoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoPagoLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(dialogoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoPagoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(48, Short.MAX_VALUE))
                            .addGroup(dialogoPagoLayout.createSequentialGroup()
                                .addComponent(radioTrajeta)
                                .addGap(43, 43, 43)
                                .addComponent(radioTrasferencia))))
                    .addGroup(dialogoPagoLayout.createSequentialGroup()
                        .addGroup(dialogoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialogoPagoLayout.createSequentialGroup()
                                .addGroup(dialogoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(dialogoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(dialogoPagoLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(textTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dialogoPagoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(dialogoPagoLayout.createSequentialGroup()
                .addGroup(dialogoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoPagoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(dialogoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dialogoPagoLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(textNombreApellido))))
                    .addGroup(dialogoPagoLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(dialogoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoPagoLayout.createSequentialGroup()
                                .addComponent(labelcvu)
                                .addGap(9, 9, 9))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(dialogoPagoLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        dialogoPagoLayout.setVerticalGroup(
            dialogoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoPagoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dialogoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioTrajeta)
                    .addComponent(radioTrasferencia))
                .addGap(29, 29, 29)
                .addGroup(dialogoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(dialogoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(dialogoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dialogoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textNombreApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelcvu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(btnPagar)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dialogoPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dialogoPago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
       if (validaciones()) {
            try {
                JOptionPane.showMessageDialog(this, 
                    "Procesando pago...\nPor favor espere.", 
                    "Procesando", 
                    JOptionPane.INFORMATION_MESSAGE);
                
                Thread.sleep(1500);
                
                JOptionPane.showMessageDialog(this, 
                    "Pago procesado exitosamente\n\n" +
                    (radioTrajeta.isSelected() ? 
                     "Método: Tarjeta terminada en " + textTarjeta.getText().substring(textTarjeta.getText().length() - 4) :
                     "Método: Transferencia - Envíe comprobante"), 
                    "Pago Exitoso", 
                    JOptionPane.INFORMATION_MESSAGE);
                
                this.pago = true;
                this.dispose();
                
            } catch (InterruptedException ex) {
                JOptionPane.showMessageDialog(this, 
                    "Error en el procesamiento del pago", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
                this.pago = false;
            }
        } else {
            this.pago = false;
        }

    }//GEN-LAST:event_btnPagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagoTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagoTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagoTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagoTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PagoTarjeta dialog = new PagoTarjeta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnPagar;
    private javax.swing.JPanel dialogoPago;
    private com.toedter.calendar.JDateChooser fechaVencimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelcvu;
    private javax.swing.JRadioButton radioTrajeta;
    private javax.swing.JRadioButton radioTrasferencia;
    private javax.swing.JTextField textCodigo;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textNombreApellido;
    private javax.swing.JTextField textTarjeta;
    // End of variables declaration//GEN-END:variables

  
}
