/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.DiaDeSpa;
import Modelo.Turno;
import Persistencia.DiaDeSpaData;
import Persistencia.TurnoData;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anitabonita
 */
public class VistaDiaDeSpaCompleto extends javax.swing.JInternalFrame {
    private DiaDeSpaData dias= new DiaDeSpaData();
    private TurnoData turnos= new TurnoData();
    private DefaultTableModel modeloSpa;
    private DefaultTableModel modeloSesion;
    /**
     * Creates new form VistaDiaDeSpaCompleto
     */
    public VistaDiaDeSpaCompleto() {
        initComponents();
    modeloSpa = new DefaultTableModel(
        new String[]{"codPack", "FechaHora", "Preferencias", "Cliente", "Estado", "Monto"},
        0
    );
    jtSpa.setModel(modeloSpa);

    modeloSesion = new DefaultTableModel(
    new String[]{
        "codSesion",
        "Fecha Inicio",      
        "Hora Inicio",       
        "Hora Fin",        
        "Tratamiento",
        "Consultorio",
        "Especialista",
        "Instalación",
        "Estado"
    },
    0
);
    jtsesion.setModel(modeloSesion);

    jtSpa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    
    jtSpa.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            filaSpaSeleccionado();
        }
    });
    cargarDiasSpa();
    }

    private void cargarDiasSpa() {
    modeloSpa.setRowCount(0); 
    List<DiaDeSpa> lista = dias.listarDiasDeSpa(); 
    for (DiaDeSpa d : lista) {
        modeloSpa.addRow(new Object[]{
            d.getCodPack(),
            d.getFechaYHora(),
            d.getPreferencias(),
            d.getCliente().getNombreCompleto(),
            d.isEstado()? "Activo" : "Inactivo",
            String.format("%.2f",d.getMonto())
        });
    }
}
   private void filaSpaSeleccionado() {
    int fila = jtSpa.getSelectedRow();
    if (fila >= 0) {
        Object o = modeloSpa.getValueAt(fila, 0);  
        if (o != null) {
            int codPack = (o instanceof Integer) ? ((Integer)o).intValue() : Integer.parseInt(o.toString());
            cargarSesiones(codPack);
        }
    }
}
    private void cargarSesiones(int codPack) {
    modeloSesion.setRowCount(0);
    List<Turno> sesiones = turnos.buscarSesionesConNombresPorDiaSpa(codPack);
    for (Turno s : sesiones) {
        LocalDateTime inicio = s.getFechaYHoraDeInicio();
        LocalDateTime fin = s.getFechaYHoraDeFin();

        // Extraer las partes
        String fechaInicio = inicio.toLocalDate().toString();   
        String horaInicio = inicio.toLocalTime().toString();    
        String horaFin = fin.toLocalTime().toString();          
        modeloSesion.addRow(new Object[]{
            s.getCodSesion(),
            fechaInicio,
            horaInicio,
            horaFin,
            s.getTratamiento().getNombre(),
            s.getConsultorio().getNroConsultorio(),
            s.getEspecialista().getNombreYApellido(),  
            s.getInstalacion().getNombre(),
            s.isEstado()? "Activo" : "Inactivo"   
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtSpa = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtsesion = new javax.swing.JTable();
        jbSalir = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("<html><u>Seleccione un dia de spa:</u></html>");

        jtSpa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtSpa);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("<html><u>A continuacion se muestra las sesiones del dia de spa:</u></html>");

        jtsesion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtsesion);

        jbSalir.setBackground(new java.awt.Color(0, 153, 255));
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbSalir)
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jbSalir;
    private javax.swing.JTable jtSpa;
    private javax.swing.JTable jtsesion;
    // End of variables declaration//GEN-END:variables
}
