/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Tratamiento;
import Modelo.Turno;
import Persistencia.ConsultorioData;
import Persistencia.DiaDeSpaData;
import Persistencia.EspecialistaData;
import Persistencia.InstalacionData;
import Persistencia.TurnoData;
import Persistencia.TratamientoData;
import java.awt.Dimension;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author esteb
 */
public class VistaTurno extends javax.swing.JInternalFrame {

    private Turno turno = null;
    private TurnoData turnodata = new TurnoData();
    private TratamientoData tratamientod = new TratamientoData();
    private ConsultorioData consultoriod = new ConsultorioData();
    private EspecialistaData especialistad = new EspecialistaData();
    private InstalacionData instalaciond = new InstalacionData();
    private DiaDeSpaData diadespad = new DiaDeSpaData();
    private DefaultTableModel modeloTabla = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int column) {
            return column == 1 || column == 2;
        }
    };

    /**
     * Creates new form VistaSesion
     */
    public VistaTurno() {
        initComponents();
        armarCabecera();
        cargarTratamientosPorTipo(null);
                
        // Agrupar radio buttons para que sean exclusivos
        ButtonGroup grupoTipos = new ButtonGroup();
        grupoTipos.add(radioFacial);
        grupoTipos.add(radioCorporal);
        grupoTipos.add(radioEstetico);
        grupoTipos.add(radioRelajacion);

        // Agregar listeners a los radio buttons
        radioFacial.addActionListener(this::radioFacialActionPerformed);
        radioEstetico.addActionListener(this::radioEsteticoActionPerformed);
        radioCorporal.addActionListener(this::radioCorporalActionPerformed);
        radioRelajacion.addActionListener(this::radioRelajacionActionPerformed);

    }

    
    private void armarCabecera() {
        modeloTabla.addColumn("Código");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Detalle");
        modeloTabla.addColumn("Duración");
        modeloTabla.addColumn("Precio");
        tablaTratamientos.setModel(modeloTabla);

        tablaTratamientos.removeColumn(tablaTratamientos.getColumnModel().getColumn(0));

    }

    private void cargarTratamientosPorTipo(String tipo) {
        modeloTabla.setRowCount(0);

        List<Tratamiento> tratamientos;
        if (tipo == null || tipo.isEmpty()) {
            tratamientos = tratamientod.listarTodosTratamientos();
        } else {
            tratamientos = tratamientod.listarTratamientosPorTipo(tipo);
        }

        for (Tratamiento t : tratamientos) {
            Object[] fila = {
                t.getCodTratam(),
                t.getNombre(),
                t.getDetalle(),
                t.getDuracion() + " min",
                "$" + String.format("%.2f", t.getCosto())
            };
            modeloTabla.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTratamientos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        radioFacial = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        radioCorporal = new javax.swing.JRadioButton();
        radioRelajacion = new javax.swing.JRadioButton();
        radioEstetico = new javax.swing.JRadioButton();
        btnReservar = new javax.swing.JButton();
        btnContacto = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTree1);

        setTitle("Gestion de Turnos");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        tablaTratamientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaTratamientos.setToolTipText("");
        jScrollPane2.setViewportView(tablaTratamientos);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 51));
        jLabel3.setText("<html><u>Servicios Disponibles</u></html>");

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("(Seleccione el tratamiento de su interes para consultar o hacer una reserva)");

        radioFacial.setText("Facial");
        radioFacial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFacialActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo de Tratamiento:");

        radioCorporal.setText("Corporal");
        radioCorporal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCorporalActionPerformed(evt);
            }
        });

        radioRelajacion.setText("Relajacion");
        radioRelajacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRelajacionActionPerformed(evt);
            }
        });

        radioEstetico.setText("Estetico");
        radioEstetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEsteticoActionPerformed(evt);
            }
        });

        btnReservar.setBackground(new java.awt.Color(255, 153, 102));
        btnReservar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReservar.setForeground(new java.awt.Color(0, 0, 0));
        btnReservar.setText("Reservar");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        btnContacto.setBackground(new java.awt.Color(255, 153, 102));
        btnContacto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnContacto.setForeground(new java.awt.Color(0, 0, 0));
        btnContacto.setText("Contacto");
        btnContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactoActionPerformed(evt);
            }
        });

        btnConsultar.setBackground(new java.awt.Color(255, 153, 102));
        btnConsultar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Para Consultas o mas Informacion, contactanos!");

        btnSalir.setBackground(new java.awt.Color(255, 153, 102));
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(btnReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioFacial)
                                .addGap(27, 27, 27)
                                .addComponent(radioCorporal)
                                .addGap(27, 27, 27)
                                .addComponent(radioRelajacion)
                                .addGap(18, 18, 18)
                                .addComponent(radioEstetico))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(31, 31, 31)
                                .addComponent(btnContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalir)))))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioFacial)
                    .addComponent(jLabel2)
                    .addComponent(radioCorporal)
                    .addComponent(radioRelajacion)
                    .addComponent(radioEstetico))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnContacto)
                    .addComponent(btnSalir))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioFacialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFacialActionPerformed
        // TODO add your handling code here:
        cargarTratamientosPorTipo("Facial");
    }//GEN-LAST:event_radioFacialActionPerformed

    private void radioRelajacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRelajacionActionPerformed
        // TODO add your handling code here:
        cargarTratamientosPorTipo("Relajacion");
    }//GEN-LAST:event_radioRelajacionActionPerformed

    private void radioEsteticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEsteticoActionPerformed
        // TODO add your handling code here:
        cargarTratamientosPorTipo("Estetico");
    }//GEN-LAST:event_radioEsteticoActionPerformed

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        int filaSeleccionada = tablaTratamientos.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un tratamiento para reservar");
            return;
        }

        int codigoTratamiento = (int) modeloTabla.getValueAt(filaSeleccionada, 0);
        Tratamiento tratamiento = tratamientod.buscarTratamiento(codigoTratamiento);

        if (tratamiento != null) {
            ReservarSesion reserva = new ReservarSesion(tratamiento);
            reserva.setVisible(true);

            javax.swing.JDesktopPane desktop = (javax.swing.JDesktopPane) this.getParent();
            desktop.add(reserva);  

            java.awt.Dimension desktopSize = desktop.getSize();
            java.awt.Dimension jifSize = reserva.getSize();
            reserva.setLocation((desktopSize.width - jifSize.width) / 2,
                    (desktopSize.height - jifSize.height) / 2);
                    reserva.toFront();

        } else {
            JOptionPane.showMessageDialog(this, "Error: No se encontró el tratamiento seleccionado");
        }
    }//GEN-LAST:event_btnReservarActionPerformed

    private void btnContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactoActionPerformed
        // TODO add your handling code here
        String contacto
                = "SPA ENTRE DEDOS\n\n"
                + "Dirección:\n"
                + "Av. Siempre Viva 123. "
                + "Centro Comercial 'El Descanso'\n"
                + "Local 45, Planta Baja\n\n"
                + "Teléfonos: "
                + "(351) 422-7890  -  "
                + "+54 9 351 512-3456\n\n"
                + "Email:\n"
                + "Para mas informacion: info@spaentrededos.com\n"
                + "Para Reservas: reservas@spaentrededos.com\n\n"
                + "Horarios de Atencion:\n"
                + "Lun-Vie: 9:00-21:00 hs\n"
                + "Sabados: 9:00-16:00 hs\n"
                + "Domingos: Cerrado";

        JOptionPane.showMessageDialog(this,
                contacto,
                "Contacto - Spa Entre Dedos",
                JOptionPane.INFORMATION_MESSAGE);
        this.dispose();

    }//GEN-LAST:event_btnContactoActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        int filaSeleccionada = tablaTratamientos.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un tratamiento para consultar");
            return;
        }

        try {
            int codigoTratamiento = (int) modeloTabla.getValueAt(filaSeleccionada, 0);
            Tratamiento tratamiento = tratamientod.buscarTratamiento(codigoTratamiento);

            if (tratamiento != null) {
                String mensaje
                        = "Tratamiento: " + tratamiento.getNombre() + "\n\n"
                        + "INFORMACION:\n"
                        + "• Tipo: " + tratamiento.getTipo() + "\n"
                        + "• Duración: " + tratamiento.getDuracion() + " minutos\n"
                        + "• Precio: $" + String.format("%.2f", tratamiento.getCosto()) + "\n"
                        + "• Estado: " + (tratamiento.isActivo() ? "Disponible" : "No disponible") + "\n\n"
                        + "DETALLES:\n"
                        + tratamiento.getDetalle();

                if (tratamiento.getProductos() != null && !tratamiento.getProductos().trim().isEmpty()) {
                    mensaje += "\n\nPRODUCTOS:\n" + tratamiento.getProductos();
                }

                JOptionPane.showMessageDialog(this,
                        mensaje,
                        "Consulta: " + tratamiento.getNombre(),
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error: No se encontró el tratamiento seleccionado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al consultar: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnConsultarActionPerformed

    private void radioCorporalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCorporalActionPerformed
        // TODO add your handling code here:
        cargarTratamientosPorTipo("Corporal");
    }//GEN-LAST:event_radioCorporalActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnContacto;
    private javax.swing.JButton btnReservar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    private javax.swing.JRadioButton radioCorporal;
    private javax.swing.JRadioButton radioEstetico;
    private javax.swing.JRadioButton radioFacial;
    private javax.swing.JRadioButton radioRelajacion;
    private javax.swing.JTable tablaTratamientos;
    // End of variables declaration//GEN-END:variables

}
