/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.DiaDeSpa;
import Persistencia.ClienteData;
import Persistencia.DiaDeSpaData;
import Persistencia.TurnoData;
import static java.awt.SystemColor.desktop;
import java.sql.Timestamp;
import java.util.Date;
import java.time.LocalDateTime;
import java.time.ZoneId;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author esteb
 */
public class VistaDiaDeSpa extends javax.swing.JInternalFrame {

    private DiaDeSpa diadespa = null;
    private DiaDeSpaData diadespadata = new DiaDeSpaData();
    private ClienteData cd = new ClienteData();
    private TurnoData sd = new TurnoData();
    private DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int column) {
            return column == 1 || column == 2 || column == 6;
        }
    };

    /**
     * Creates new form VistaDiaDeSpa
     */
    public VistaDiaDeSpa() {
        initComponents();
        armarCabecera();
        cargarDatos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBBorrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDiaDeSpa = new javax.swing.JTable();
        jBActualizar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jDDiaDeSpa = new com.toedter.calendar.JDateChooser();
        jBRefrescar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnAgregaDia = new javax.swing.JButton();
        jBFecha = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jCEstado = new javax.swing.JComboBox<>();
        jBEstado = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setTitle("Dia de Spa");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jBBorrar.setBackground(new java.awt.Color(255, 153, 102));
        jBBorrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBBorrar.setForeground(new java.awt.Color(255, 255, 255));
        jBBorrar.setText("Borrar");
        jBBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBBorrarMouseClicked(evt);
            }
        });

        jTDiaDeSpa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTDiaDeSpa);

        jBActualizar.setBackground(new java.awt.Color(255, 153, 102));
        jBActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBActualizar.setForeground(new java.awt.Color(255, 255, 255));
        jBActualizar.setText("Modificar");
        jBActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBActualizarMouseClicked(evt);
            }
        });
        jBActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarActionPerformed(evt);
            }
        });

        jBSalir.setBackground(new java.awt.Color(255, 153, 102));
        jBSalir.setForeground(new java.awt.Color(255, 255, 255));
        jBSalir.setText("X");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 102));
        jLabel2.setText("Dia de Spa");

        jDDiaDeSpa.setForeground(new java.awt.Color(255, 102, 51));

        jBRefrescar.setBackground(new java.awt.Color(255, 153, 102));
        jBRefrescar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBRefrescar.setForeground(new java.awt.Color(255, 255, 255));
        jBRefrescar.setText("Refrescar Tabla");
        jBRefrescar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBRefrescarMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 102));
        jLabel3.setText("Fecha:");

        btnAgregaDia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregaDia.setForeground(new java.awt.Color(255, 153, 102));
        btnAgregaDia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pngtree-lovely-girl-spa-massage-concept-illustration-png-image_6938773 (1).png"))); // NOI18N
        btnAgregaDia.setText("Contratar Dia de Spa");
        btnAgregaDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregaDiaActionPerformed(evt);
            }
        });

        jBFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icone-loupe-orange (1) (1) (1).png"))); // NOI18N
        jBFecha.setText("Buscar");
        jBFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBFechaMouseClicked(evt);
            }
        });
        jBFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFechaActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setText("Estado");

        jCEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        jBEstado.setBackground(new java.awt.Color(255, 153, 102));
        jBEstado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBEstado.setForeground(new java.awt.Color(255, 255, 255));
        jBEstado.setText("Cambiar Estado");
        jBEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBEstadoMouseClicked(evt);
            }
        });
        jBEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBSalir)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addComponent(jDDiaDeSpa, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jBFecha)
                        .addGap(124, 124, 124)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jBBorrar)
                                        .addGap(166, 166, 166))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBActualizar)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jCEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBRefrescar)
                                        .addGap(19, 19, 19))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(jBEstado)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(btnAgregaDia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBSalir)
                        .addGap(41, 41, 41)
                        .addComponent(jBFecha))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDDiaDeSpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBBorrar)
                    .addComponent(jBActualizar)
                    .addComponent(jBRefrescar))
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jBEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnAgregaDia)
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBBorrarMouseClicked
        // TODO add your handling code here:
        borrarDiaDeSpa();
    }//GEN-LAST:event_jBBorrarMouseClicked

    private void jBActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBActualizarMouseClicked
        // TODO add your handling code here:
        guardarCambiosDesdeTabla();
    }//GEN-LAST:event_jBActualizarMouseClicked

    private void jBRefrescarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBRefrescarMouseClicked
        // TODO add your handling code here:
        cargarDatos();
    }//GEN-LAST:event_jBRefrescarMouseClicked

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBFechaMouseClicked
        // TODO add your handling code here:
        buscarPorFecha();
    }//GEN-LAST:event_jBFechaMouseClicked

    private void btnAgregaDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregaDiaActionPerformed
        // TODO add your handling code here:
        AgregarDiaDeSpa dia = new AgregarDiaDeSpa();
        dia.setVisible(true);

        java.awt.Container parent = this.getParent();
        if (parent instanceof javax.swing.JDesktopPane) {
            parent.add(dia);

            java.awt.Dimension desktopSize = parent.getSize();
            java.awt.Dimension jifSize = dia.getSize();
            dia.setLocation((desktopSize.width - jifSize.width) / 2,
                    (desktopSize.height - jifSize.height) / 2);
            dia.toFront();
        } else {

            javax.swing.JFrame frame = new javax.swing.JFrame("Agregar Dia de Spa");
            frame.setContentPane(dia.getContentPane());
            frame.pack();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        }
    }//GEN-LAST:event_btnAgregaDiaActionPerformed

    private void jBFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBFechaActionPerformed

    private void jBActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBActualizarActionPerformed

    private void jBEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEstadoActionPerformed
        // TODO add your handling code here:
        cambiarEstadoDiaDeSpa();
    }//GEN-LAST:event_jBEstadoActionPerformed

    private void jBEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBEstadoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jBEstadoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregaDia;
    private javax.swing.JButton jBActualizar;
    private javax.swing.JButton jBBorrar;
    private javax.swing.JButton jBEstado;
    private javax.swing.JButton jBFecha;
    private javax.swing.JButton jBRefrescar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox<String> jCEstado;
    private com.toedter.calendar.JDateChooser jDDiaDeSpa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTDiaDeSpa;
    // End of variables declaration//GEN-END:variables
private void armarCabecera() {

        modelo.addColumn("CodPack");
        modelo.addColumn("Fecha y Hora");
        modelo.addColumn("Preferencias");
        modelo.addColumn("Cliente");
        modelo.addColumn("Estado");
        modelo.addColumn("Monto");

        jTDiaDeSpa.setModel(modelo);

    }

    private void cargarDatos() {
        String activo;
        modelo.setRowCount(0);
        for (DiaDeSpa d : diadespadata.listarDiasDeSpa()) {

            if (d.isEstado()) {
                activo = "Activo";
            } else {
                activo = "Inactivo";
            }

            modelo.addRow(new Object[]{d.getCodPack(), d.getFechaYHora(), d.getPreferencias(), d.getCliente().getCodCli(), activo, d.getMonto()});
        }
    }

    private void buscarPorFecha() {

        try {
            java.util.Date fecha = jDDiaDeSpa.getDate();
            modelo.setRowCount(0);

            if (fecha == null) {
                JOptionPane.showMessageDialog(this, "Debe ingresar la fecha", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }
            java.sql.Date fechaSQL = new java.sql.Date(fecha.getTime());
            diadespa = diadespadata.buscarDiaDeSpaPorFecha(fechaSQL);
            String activo;
            if (diadespa != null) {

                if (diadespa.isEstado()) {
                    activo = "Activo";
                } else {
                    activo = "Inactivo";
                }
                modelo.addRow(new Object[]{diadespa.getCodPack(), diadespa.getFechaYHora(), diadespa.getPreferencias(), diadespa.getCliente().getCodCli(), activo, diadespa.getMonto()});

                jDDiaDeSpa.setDate(null);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error al ingresar la fecha", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void borrarDiaDeSpa() {
        int fila = jTDiaDeSpa.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "seleccione un día de spa a eliminar", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

        if (fila != -1) {
            int conf = JOptionPane.showConfirmDialog(
                    this,
                    "¿Seguro que desea eliminar el dia de spa seleccionado?", "Advertencia", JOptionPane.YES_NO_OPTION);

            if (conf == JOptionPane.YES_OPTION) {
                try {
                    int codPack = (int) jTDiaDeSpa.getValueAt(fila, 0);

                    diadespadata.eliminarDiaDeSpa(codPack);

                    modelo.removeRow(fila);

                    JOptionPane.showMessageDialog(this, "día de spa eliminado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,
                            "Error al eliminar el día de spa: " + e.getMessage(),
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }

    private void guardarCambiosDesdeTabla() {

    int fila = jTDiaDeSpa.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar un día de spa.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {

        //Tomar datos de la tabla
        int codPack = Integer.parseInt(modelo.getValueAt(fila, 0).toString());

        Object valorFecha = modelo.getValueAt(fila, 1);
        LocalDateTime fechaYHora = null;

        if (valorFecha instanceof Timestamp) {
            fechaYHora = ((Timestamp) valorFecha).toLocalDateTime();
        } else if (valorFecha instanceof java.util.Date) {
            fechaYHora = ((java.util.Date) valorFecha).toInstant()
                    .atZone(ZoneId.systemDefault())
                    .toLocalDateTime();
        } else {
            fechaYHora = LocalDateTime.parse(valorFecha.toString().trim());
        }

        String preferencias = modelo.getValueAt(fila, 2).toString().trim();
        if (!preferencias.matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$")) {
                JOptionPane.showMessageDialog(this, "Las preferencias solo deben contener letras y espacios.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        int codCli = Integer.parseInt(modelo.getValueAt(fila, 3).toString());

        String estadoStr = modelo.getValueAt(fila, 4).toString();
        boolean estado = estadoStr.equalsIgnoreCase("Activo");

        double monto = Double.parseDouble(modelo.getValueAt(fila, 5).toString());

        
        DiaDeSpa dia = new DiaDeSpa();
        dia.setCodPack(codPack);
        dia.setFechaYHora(fechaYHora);
        dia.setPreferencias(preferencias);
        dia.setCliente(cd.buscarCliente(codCli));
        dia.setMonto(monto);
        dia.setEstado(estado);

        
        diadespadata.actualizarDiaDeSpa(dia);

        

        cargarDatos();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al actualizar día de spa:\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    private void cambiarEstadoDiaDeSpa() {
        int fila = jTDiaDeSpa.getSelectedRow();
        DiaDeSpa aux = new DiaDeSpa();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un día de spa", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        //validacion para la conversion del valor de la tabla
        Object valorFecha = modelo.getValueAt(fila, 1);
        LocalDateTime fechaHora = null;

        if (valorFecha instanceof java.sql.Timestamp) {
            fechaHora = ((Timestamp) valorFecha).toLocalDateTime();
        } else if (valorFecha instanceof java.util.Date) {
            fechaHora = ((java.util.Date) valorFecha).toInstant()
                    .atZone(ZoneId.systemDefault())
                    .toLocalDateTime();
        } else if (valorFecha instanceof String) {
            fechaHora = LocalDateTime.parse((String) valorFecha);
        }

        aux.setFechaYHora(fechaHora);

        aux.setCodPack(Integer.parseInt(modelo.getValueAt(fila, 0).toString()));
        aux.setFechaYHora(fechaHora);
        aux.setPreferencias((String) modelo.getValueAt(fila, 2));
        aux.setCliente(cd.buscarCliente(Integer.parseInt(modelo.getValueAt(fila, 3).toString())));
        aux.setSesiones(sd.ListarTurnos());
        aux.setMonto(Double.parseDouble(modelo.getValueAt(fila, 5).toString()));
        
        String estadoActual = modelo.getValueAt(fila, 4).toString();
        String nuevoEstado = (String) jCEstado.getSelectedItem();
        boolean estadoBoolean = nuevoEstado.equalsIgnoreCase("Activo");
         if (estadoActual.equalsIgnoreCase(nuevoEstado)) {
        JOptionPane.showMessageDialog(this, "El dia de spa ya está en ese estado.", "Información", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

        try {
           diadespadata.cambiarEstadoDiaDeSpa(aux.getCodPack(),estadoBoolean);
            cargarDatos();

            JOptionPane.showMessageDialog(this, "Estado del día de spa cambio a: " + nuevoEstado, "Exito", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cambiar estado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}
