/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


import Modelo.Sesion;
import Persistencia.ConsultorioData;
import Persistencia.DiaDeSpaData;
import Persistencia.EspecialistaData;
import Persistencia.InstalacionData;
import Persistencia.SesionData;
import Persistencia.TratamientoData;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author esteb
 */
public class VistaSesion extends javax.swing.JInternalFrame {
    private Sesion sesion = null;
    private SesionData sesiondata = new SesionData();
    private TratamientoData tratamientod = new TratamientoData();
    private ConsultorioData consultoriod = new ConsultorioData();
    private EspecialistaData especialistad = new EspecialistaData();
    private InstalacionData instalaciond = new InstalacionData();
    private DiaDeSpaData diadespad = new DiaDeSpaData();
    private DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int column) {
            return false;
        }
    };

    /**
     * Creates new form VistaSesion
     */
    public VistaSesion() {
        initComponents();
        armarCabecera();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTCodSesion = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTSesiones = new javax.swing.JTable();
        jBBorrar = new javax.swing.JButton();
        jBActualizar = new javax.swing.JButton();
        jBRefrescar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jCEstado = new javax.swing.JComboBox<>();
        jBEstado = new javax.swing.JButton();

        jLabel1.setText("CodSesion:");

        jBBuscar.setText("Buscar");
        jBBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBBuscarMouseClicked(evt);
            }
        });

        jTSesiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTSesiones);

        jBBorrar.setText("Borrar");
        jBBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBBorrarMouseClicked(evt);
            }
        });

        jBActualizar.setText("Actualizar");
        jBActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBActualizarMouseClicked(evt);
            }
        });

        jBRefrescar.setText("Refrescar Tabla");
        jBRefrescar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBRefrescarMouseClicked(evt);
            }
        });

        jLabel2.setText("Estado:");

        jCEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        jBEstado.setText("Editar Estado");
        jBEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBEstadoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(229, 229, 229)
                            .addComponent(jBBorrar)
                            .addGap(18, 18, 18)
                            .addComponent(jBActualizar)
                            .addGap(18, 18, 18)
                            .addComponent(jBRefrescar))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addComponent(jLabel1)
                            .addGap(120, 120, 120)
                            .addComponent(jTCodSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(155, 155, 155)
                            .addComponent(jBBuscar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2)
                        .addGap(60, 60, 60)
                        .addComponent(jCEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jBEstado)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTCodSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBBuscar)))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBBorrar)
                    .addComponent(jBActualizar)
                    .addComponent(jBRefrescar))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEstado))
                .addGap(0, 193, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBBuscarMouseClicked
        // TODO add your handling code here:
        buscarPorCodSesion();
    }//GEN-LAST:event_jBBuscarMouseClicked

    private void jBBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBBorrarMouseClicked
        // TODO add your handling code here:
        borrarSesion();
    }//GEN-LAST:event_jBBorrarMouseClicked

    private void jBActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBActualizarMouseClicked
        // TODO add your handling code here:
        guardarCambiosDesdeTabla();
    }//GEN-LAST:event_jBActualizarMouseClicked

    private void jBRefrescarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBRefrescarMouseClicked
        // TODO add your handling code here
        cargarDatos();
    }//GEN-LAST:event_jBRefrescarMouseClicked

    private void jBEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBEstadoMouseClicked
        // TODO add your handling code here:
        cambiarEstadoSesion();
    }//GEN-LAST:event_jBEstadoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBActualizar;
    private javax.swing.JButton jBBorrar;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEstado;
    private javax.swing.JButton jBRefrescar;
    private javax.swing.JComboBox<String> jCEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCodSesion;
    private javax.swing.JTable jTSesiones;
    // End of variables declaration//GEN-END:variables
private void armarCabecera() {

        modelo.addColumn("CodSesion");
        modelo.addColumn("Fecha y Hora inicio");
        modelo.addColumn("Fecha y Hora fin");
        modelo.addColumn("código Tratamiento");
        modelo.addColumn("número consultorio");
        modelo.addColumn("matricula masajista");
        modelo.addColumn("código instalación");
        modelo.addColumn("código pack");
        modelo.addColumn("Estado");

        jTSesiones.setModel(modelo);

    }
private void cargarDatos() {
        String activo;
        modelo.setRowCount(0);
        for (Sesion s : sesiondata.listarSesiones()) {

            if (s.isEstado()) {
                activo = "Activo";
            } else {
                activo = "Inactivo";
            }
            modelo.addRow(new Object[]{s.getCodSesion(),s.getFechaYHoraDeInicio(),s.getFechaYHoraDeFin(),s.getTratamiento().getCodTratam(),s.getConsultorio().getNroConsultorio(),
                s.getEspecialista().getMatricula(),s.getInstalacion().getCodInstal(),s.getDiaDeSpa().getCodPack(),activo});
        }
    }
private void buscarPorCodSesion() {

        try {
            String codSesion = (jTCodSesion.getText().trim());
            modelo.setRowCount(0);

            if (codSesion.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese un código de sesión para buscar", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }
            modelo.setRowCount(0);

            sesion = sesiondata.buscarSesion(Integer.parseInt(codSesion));
            String activo;
            if (sesion != null) {

                if (sesion.isEstado()) {
                    activo = "Activo";
                } else {
                    activo = "Inactivo";
                }
                 modelo.addRow(new Object[]{sesion.getCodSesion(),sesion.getFechaYHoraDeInicio(),sesion.getFechaYHoraDeFin(),sesion.getTratamiento().getCodTratam(),sesion.getConsultorio().getNroConsultorio(),
                sesion.getEspecialista().getMatricula(),sesion.getInstalacion().getCodInstal(),sesion.getDiaDeSpa().getCodPack(),activo});

                jTCodSesion.setText("");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error al ingresar el código de la sesión", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }
private void borrarSesion() {
        int fila = jTSesiones.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "seleccione una sesión a eliminar", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

        if (fila != -1) {
            int conf = JOptionPane.showConfirmDialog(
                    this,
                    "¿Seguro que desea eliminar la sesión seleccionada?", "Advertencia", JOptionPane.YES_NO_OPTION);

            if (conf == JOptionPane.YES_OPTION) {
                try {
                    int codSesion = (int) jTSesiones.getValueAt(fila, 0);

                    sesiondata.borrarSesion(codSesion);

                    modelo.removeRow(fila);

                    JOptionPane.showMessageDialog(this, "Sesión eliminada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,
                            "Error al eliminar la sesión: " + e.getMessage(),
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }
 private void guardarCambiosDesdeTabla() {
        int filaSeleccionada = jTSesiones.getSelectedRow();
        

        try {
            // obtener datos de la fila seleccionada
            int codSesion = Integer.parseInt(modelo.getValueAt(filaSeleccionada, 0).toString());
            LocalDateTime fechaYHoraInicio = LocalDateTime.parse(modelo.getValueAt(filaSeleccionada, 1).toString().trim());
            LocalDateTime fechaYHoraFin = LocalDateTime.parse(modelo.getValueAt(filaSeleccionada, 2).toString().trim());
            int codTratam = Integer.parseInt(modelo.getValueAt(filaSeleccionada, 3).toString());
            int nroConsultorio = Integer.parseInt(modelo.getValueAt(filaSeleccionada, 4).toString().trim());
            String matriculaMasajista = modelo.getValueAt(filaSeleccionada, 5).toString();
            int codInstalacion = Integer.parseInt(modelo.getValueAt(filaSeleccionada, 6).toString().trim());
            int codPack = Integer.parseInt(modelo.getValueAt(filaSeleccionada, 7).toString().trim());
            String estadoStr = modelo.getValueAt(filaSeleccionada, 8).toString().trim();
            boolean estado = estadoStr.equals("Activo");

            Sesion sesionactualizada = new Sesion(fechaYHoraInicio, fechaYHoraFin, tratamientod.buscarTratamiento(codTratam),consultoriod.buscarConsultorio(nroConsultorio),especialistad.buscarEspecialista(matriculaMasajista), 
            instalaciond.buscarInstalacion(codInstalacion),diadespad.buscarDiaDeSpa(codPack),estado);
            sesionactualizada.setCodSesion(codSesion);

            sesiondata.actualizarSesion(sesionactualizada);

            JOptionPane.showMessageDialog(this, "Sesión actualizada correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            cargarDatos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar sesión: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
 private void cambiarEstadoSesion() {
        int fila = jTSesiones.getSelectedRow();
        Sesion aux = new Sesion();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una sesión", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        aux.setCodSesion((int) modelo.getValueAt(fila, 0));
        aux.setFechaYHoraDeInicio((LocalDateTime) modelo.getValueAt(fila, 1));
        aux.setFechaYHoraDeFin((LocalDateTime) modelo.getValueAt(fila, 2));
        aux.setTratamiento(tratamientod.buscarTratamiento((int) modelo.getValueAt(fila, 3)));
        aux.setConsultorio(consultoriod.buscarConsultorio((int) modelo.getValueAt(fila, 4)));
        aux.setEspecialista(especialistad.buscarEspecialista((String) modelo.getValueAt(fila, 5)));
        aux.setInstalacion(instalaciond.buscarInstalacion((int) modelo.getValueAt(fila, 6)));
        aux.setDiaDeSpa(diadespad.buscarDiaDeSpa((int) modelo.getValueAt(fila, 7)));

        String nuevoEstado = (String) jCEstado.getSelectedItem();
        boolean estadoBoolean = nuevoEstado.equals("Activo");

        try {
            if (estadoBoolean) {

                sesiondata.habilitarSesion(aux);
 
            } else {

                sesiondata.deshabilitarSesion(aux);

            }
            cargarDatos();

            JOptionPane.showMessageDialog(this, "Estado de la sesión cambio a: " + nuevoEstado, "Exito", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cambiar estado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}
