/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Cliente;
import Persistencia.ClienteData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anitabonita
 */
public class VistaCliente extends javax.swing.JInternalFrame {

    private Cliente clienteAc = null;
    private ClienteData clientedata = new ClienteData();

    private DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int column) {
            return column == 1 || column == 2 || column == 3 || column == 4 || column == 5;
        }
    };

    /**
     * Creates new form VistaCliente
     */
    public VistaCliente() {
        initComponents();
        armarCabecera();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTId = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCliente = new javax.swing.JTable();
        jBBorrar = new javax.swing.JButton();
        jBActualizar = new javax.swing.JButton();
        jBRefrescar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTDni = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTAfecciones = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCEstado = new javax.swing.JComboBox<>();
        jBEstado = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTNombreC = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTEdad = new javax.swing.JTextField();
        jBAgregar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();

        textField1.setText("textField1");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setText("ID:");

        jTId.setBackground(new java.awt.Color(255, 204, 179));

        jBBuscar.setBackground(new java.awt.Color(255, 153, 102));
        jBBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jBBuscar.setText("Buscar");
        jBBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBBuscarMouseClicked(evt);
            }
        });
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jTCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTCliente);

        jBBorrar.setBackground(new java.awt.Color(255, 153, 102));
        jBBorrar.setForeground(new java.awt.Color(0, 0, 0));
        jBBorrar.setText("Borrar");
        jBBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBBorrarMouseClicked(evt);
            }
        });
        jBBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBorrarActionPerformed(evt);
            }
        });

        jBActualizar.setBackground(new java.awt.Color(255, 153, 102));
        jBActualizar.setForeground(new java.awt.Color(0, 0, 0));
        jBActualizar.setText("Actualizar");
        jBActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBActualizarMouseClicked(evt);
            }
        });
        jBActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarActionPerformed(evt);
            }
        });

        jBRefrescar.setBackground(new java.awt.Color(255, 153, 102));
        jBRefrescar.setForeground(new java.awt.Color(0, 0, 0));
        jBRefrescar.setText("Refrescar Tabla");
        jBRefrescar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBRefrescarMouseClicked(evt);
            }
        });
        jBRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRefrescarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 51));
        jLabel3.setText("<html><u>Agregar Cliente</u></html>");

        jLabel4.setForeground(new java.awt.Color(255, 102, 51));
        jLabel4.setText("DNI:");

        jTDni.setBackground(new java.awt.Color(255, 204, 179));
        jTDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDniActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 102, 51));
        jLabel6.setText("Teléfono:");

        jTTelefono.setBackground(new java.awt.Color(255, 204, 179));

        jLabel8.setForeground(new java.awt.Color(255, 102, 51));
        jLabel8.setText("Afecciones:");

        jTAfecciones.setBackground(new java.awt.Color(255, 204, 179));

        jLabel2.setForeground(new java.awt.Color(255, 102, 51));
        jLabel2.setText("Estado:");

        jCEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        jBEstado.setBackground(new java.awt.Color(255, 153, 102));
        jBEstado.setForeground(new java.awt.Color(0, 0, 0));
        jBEstado.setText("Editar Estado");
        jBEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBEstadoMouseClicked(evt);
            }
        });
        jBEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEstadoActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 102, 51));
        jLabel5.setText("Nombre Completo:");

        jTNombreC.setBackground(new java.awt.Color(255, 204, 179));
        jTNombreC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNombreCActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 102, 51));
        jLabel7.setText("Edad:");

        jTEdad.setBackground(new java.awt.Color(255, 204, 179));

        jBAgregar.setBackground(new java.awt.Color(255, 153, 102));
        jBAgregar.setForeground(new java.awt.Color(0, 0, 0));
        jBAgregar.setText("Agregar");
        jBAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBAgregarMouseClicked(evt);
            }
        });
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });

        jBSalir.setBackground(new java.awt.Color(255, 153, 102));
        jBSalir.setForeground(new java.awt.Color(0, 0, 0));
        jBSalir.setText("X");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jCEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(jBEstado)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTDni, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                                                .addComponent(jBAgregar)
                                                .addGap(21, 21, 21))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jTTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(429, 429, 429)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTAfecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))))))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jBBorrar))
                .addGap(174, 174, 174)
                .addComponent(jBActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBRefrescar)
                .addGap(53, 53, 53))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTId, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBSalir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBBuscar)))
                    .addComponent(jBSalir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBBorrar)
                    .addComponent(jBActualizar)
                    .addComponent(jBRefrescar))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEstado))
                .addGap(55, 55, 55)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTAfecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAgregar)
                    .addComponent(jTNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDniActionPerformed

    private void jBRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRefrescarActionPerformed
        // TODO add your handling code here:
        cargarDatos();
    }//GEN-LAST:event_jBRefrescarActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBorrarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jBBorrarActionPerformed

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jBAgregarActionPerformed

    private void jBActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jBActualizarActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEstadoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jBEstadoActionPerformed

    private void jBRefrescarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBRefrescarMouseClicked
        // TODO add your handling code here:
        cargarDatos();
    }//GEN-LAST:event_jBRefrescarMouseClicked

    private void jBBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBBuscarMouseClicked
        // TODO add your handling code here:
        buscarPorId();
    }//GEN-LAST:event_jBBuscarMouseClicked

    private void jBBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBBorrarMouseClicked
        // TODO add your handling code here:
        borrarCliente();
    }//GEN-LAST:event_jBBorrarMouseClicked

    private void jBActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBActualizarMouseClicked
        // TODO add your handling code here:
        guardarCambiosDesdeTabla();
    }//GEN-LAST:event_jBActualizarMouseClicked

    private void jBEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBEstadoMouseClicked
        // TODO add your handling code here:
        cambiarEstadoCliente();
    }//GEN-LAST:event_jBEstadoMouseClicked

    private void jBAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAgregarMouseClicked
        // TODO add your handling code here:
        agregarCliente();
        limpiarCampos();
    }//GEN-LAST:event_jBAgregarMouseClicked

    private void jTNombreCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNombreCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNombreCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBActualizar;
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBBorrar;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEstado;
    private javax.swing.JButton jBRefrescar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox<String> jCEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTAfecciones;
    private javax.swing.JTable jTCliente;
    private javax.swing.JTextField jTDni;
    private javax.swing.JTextField jTEdad;
    private javax.swing.JTextField jTId;
    private javax.swing.JTextField jTNombreC;
    private javax.swing.JTextField jTTelefono;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
private void armarCabecera() {

        modelo.addColumn("ID");
        modelo.addColumn("DNI");
        modelo.addColumn("Nombre Completo");
        modelo.addColumn("Teléfono");
        modelo.addColumn("Edad");
        modelo.addColumn("Afecciones");
        modelo.addColumn("Estado");

        jTCliente.setModel(modelo);

    }

    private void cargarDatos() {
        String activo;
        modelo.setRowCount(0);
        for (Cliente c : clientedata.ListarCliente()) {

            if (c.isEstado()) {
                activo = "Activo";
            } else {
                activo = "Inactivo";
            }
            modelo.addRow(new Object[]{c.getCodCli(), c.getDni(), c.getNombreCompleto(), c.getTelefono(), c.getEdad(), c.getAfecciones(), activo});
        }
    }

    private void buscarPorId() {

        try {
            String id = (jTId.getText().trim());
            modelo.setRowCount(0);

            if (id.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese un id para buscar", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }
            modelo.setRowCount(0);

            clienteAc = clientedata.buscarCliente(Integer.parseInt(id));

            if (clienteAc == null) {
                JOptionPane.showMessageDialog(this, "No se encontró ningún cliente con ese ID.", "Información", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            String activo;
            if (clienteAc != null) {

                if (clienteAc.isEstado()) {
                    activo = "Activo";
                } else {
                    activo = "Inactivo";
                }
                modelo.addRow(new Object[]{clienteAc.getCodCli(), clienteAc.getDni(), clienteAc.getNombreCompleto(), clienteAc.getTelefono(), clienteAc.getEdad(), clienteAc.getAfecciones(), activo});

                jTId.setText("");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID debe ser un número", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void borrarCliente() {
        int fila = jTCliente.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "seleccione un cliente a eliminar", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        //validar que el cliente exista
        int codcli = (int) jTCliente.getValueAt(fila, 0);
        Cliente cliente = clientedata.buscarCliente(codcli);
        if (cliente == null) {
            JOptionPane.showMessageDialog(this, "El cliente no existe o ya fue eliminado.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (fila != -1) {
            int conf = JOptionPane.showConfirmDialog(
                    this,
                    "¿Seguro que desea eliminar el cliente seleccionado?", "Advertencia", JOptionPane.YES_NO_OPTION);

            if (conf == JOptionPane.YES_OPTION) {
                try {

                    clientedata.BorrarCliente(codcli);

                    modelo.removeRow(fila);

                    JOptionPane.showMessageDialog(this, "Cliente eliminado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,
                            "Error al eliminar el cliente: " + e.getMessage(),
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }

    private void agregarCliente() {
        try {
            // Validar campos vacíos
            if (jTDni.getText().trim().isEmpty()
                    || jTNombreC.getText().trim().isEmpty()
                    || jTTelefono.getText().trim().isEmpty()
                    || jTEdad.getText().trim().isEmpty()) {

                JOptionPane.showMessageDialog(this, "Todos los campos obligatorios deben completarse.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // validar formato numerico 
            int dni = Integer.parseInt(jTDni.getText().trim());
            String nombreCompleto = jTNombreC.getText().trim();
            long telefono = Long.parseLong(jTTelefono.getText().trim());
            int edad = Integer.parseInt(jTEdad.getText().trim());
            String afecciones = jTAfecciones.getText().trim();

            // Validar rangos y longitudes
            if (dni < 1000000 || dni > 99999999) {
                JOptionPane.showMessageDialog(this, "El DNI debe tener entre 7 y 8 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (edad <= 0 || edad > 120) {
                JOptionPane.showMessageDialog(this, "La edad debe estar entre 1 y 120.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (String.valueOf(telefono).length() < 10 || String.valueOf(telefono).length() > 15) {
                JOptionPane.showMessageDialog(this, "Número de teléfono no válido.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Validar nombre (solo letras y espacios)
            if (!nombreCompleto.matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$")) {
                JOptionPane.showMessageDialog(this, "El nombre solo debe contener letras y espacios.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            // Verificar duplicado por DNI
            if (clientedata.buscarClientePorDni(dni) != null) {
                JOptionPane.showMessageDialog(this, "Ya existe un cliente con ese DNI.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Cliente c = new Cliente(dni, nombreCompleto, telefono, edad, afecciones, true);
            clientedata.guardarCliente(c);
            JOptionPane.showMessageDialog(this, "Cliente agregado correctamente.");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese valores numéricos válidos en DNI, teléfono y edad.");
        }
    }

    private void limpiarCampos() {
        jTDni.setText("");
        jTNombreC.setText("");
        jTTelefono.setText("");
        jTEdad.setText("");
        jTAfecciones.setText("");

    }

    private void guardarCambiosDesdeTabla() {
        int filaSeleccionada = jTCliente.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila para actualizar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // obtener datos de la fila seleccionada
            int codcli = Integer.parseInt(modelo.getValueAt(filaSeleccionada, 0).toString());
            int dni = Integer.parseInt(modelo.getValueAt(filaSeleccionada, 1).toString().trim());
            String nombreCompleto = modelo.getValueAt(filaSeleccionada, 2).toString().trim();
            long telefono = Long.parseLong(modelo.getValueAt(filaSeleccionada, 3).toString().trim());
            int edad = Integer.parseInt(modelo.getValueAt(filaSeleccionada, 4).toString().trim());
            String afecciones = modelo.getValueAt(filaSeleccionada, 5).toString().trim();
            String estadoStr = modelo.getValueAt(filaSeleccionada, 6).toString();
            boolean estado = estadoStr.equals("Activo");
            // Validar rangos y longitudes
            if (dni < 1000000 || dni > 99999999) {
                JOptionPane.showMessageDialog(this, "El DNI debe tener entre 7 y 8 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (edad <= 0 || edad > 120) {
                JOptionPane.showMessageDialog(this, "La edad debe estar entre 1 y 120.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (String.valueOf(telefono).length() < 10 || String.valueOf(telefono).length() > 15) {
                JOptionPane.showMessageDialog(this, "Número de teléfono no válido.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Validar nombre (solo letras y espacios)
            if (!nombreCompleto.matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$")) {
                JOptionPane.showMessageDialog(this, "El nombre solo debe contener letras y espacios.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            // Verificar duplicado por DNI
            if (clientedata.buscarClientePorDni(dni) != null) {
                JOptionPane.showMessageDialog(this, "Ya existe un cliente con ese DNI.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Cliente clienteActualizado = new Cliente(codcli, nombreCompleto, telefono, edad, afecciones, estado);
            clienteActualizado.setCodCli(codcli);

            clientedata.actualizarCliente(clienteActualizado);

            JOptionPane.showMessageDialog(this, "Cliente actualizado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            cargarDatos();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Revise los valores numéricos (DNI, teléfono, edad).", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar cliente: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cambiarEstadoCliente() {
        int fila = jTCliente.getSelectedRow();
        Cliente aux = new Cliente();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        aux.setCodCli((int) modelo.getValueAt(fila, 0));
        aux.setDni((int) modelo.getValueAt(fila, 1));
        aux.setNombreCompleto((String) modelo.getValueAt(fila, 2));
        aux.setTelefono((long) modelo.getValueAt(fila, 3));
        aux.setEdad((int) modelo.getValueAt(fila, 4));
        aux.setAfecciones((String) modelo.getValueAt(fila, 5));
        
        String estadoActual = modelo.getValueAt(fila, 6).toString();
        String nuevoEstado = (String) jCEstado.getSelectedItem();
        boolean estadoBoolean = nuevoEstado.equals("Activo");
        //validar que el estado no sea el mismo 
         if (estadoActual.equalsIgnoreCase(nuevoEstado)) {
        JOptionPane.showMessageDialog(this, "El cliente ya está en ese estado.", "Información", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

        try {
            if (estadoBoolean) {

                clientedata.HabilitarCliente(aux);

            } else {

                clientedata.DeshabilitarCliente(aux);

            }
            cargarDatos();

            JOptionPane.showMessageDialog(this, "Estado del cliente cambio a: " + nuevoEstado, "Exito", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cambiar estado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}
